<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite thread-count="50" parallel="tests" name="Failed suite [Test.Ancera.Login]" verbose="5">
  <test thread-count="50" parallel="tests" name="Test.Ancera.Login1(failed)" verbose="5">
    <classes>
      <class name="Test.Ancera.Login.TestLogin">
        <methods>
          <include name="login"/>
          <include name="logout"/>
          <include name="endreport"/>
          <include name="extent"/>
          <include name="VerifyLogout"/>
        </methods>
      </class> <!-- Test.Ancera.Login.TestLogin -->
    </classes>
  </test> <!-- Test.Ancera.Login1(failed) -->
  <test thread-count="50" parallel="tests" name="Test.Ancera.Login2(failed)" verbose="5">
    <classes>
      <class name="Test.Ancera.Login.ForgotPassword">
        <methods>
          <include name="endreport"/>
          <include name="extent"/>
          <include name="VerifyLogin"/>
          <include name="VerifyEmailReceived"/>
          <include name="SendEmailLink"/>
        </methods>
      </class> <!-- Test.Ancera.Login.ForgotPassword -->
    </classes>
  </test> <!-- Test.Ancera.Login2(failed) -->
</suite> <!-- Failed suite [Test.Ancera.Login] -->
