<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-K0SFL7M" failures="1" tests="17" name="Default test" time="475.181" errors="0" timestamp="2021-04-22T14:53:42 PKT">
  <testcase classname="Test.Ancera.Administration.OrganizationManagement" name="NavigateOM" time="20.903"/>
  <testcase classname="Test.Ancera.Administration.OrganizationManagement" name="MandatoryFieldCheck" time="157.356"/>
  <testcase classname="Test.Ancera.Administration.OrganizationManagement" name="ClosePopup" time="23.167"/>
  <testcase classname="Test.Ancera.Administration.OrganizationManagement" name="ResetButton" time="18.589"/>
  <testcase classname="Test.Ancera.Administration.OrganizationManagement" name="CreateOrganization" time="32.5"/>
  <testcase classname="Test.Ancera.Administration.OrganizationManagement" name="SearchOrganization" time="41.178"/>
  <testcase classname="Test.Ancera.Administration.OrganizationManagement" name="UpdateOrganization" time="38.861"/>
  <testcase classname="Test.Ancera.Administration.OrganizationManagement" name="SearchUpdateOrganization" time="10.448">
    <failure type="java.lang.Exception" message="java.lang.AssertionError: expected [(111) 111-1111] but found [(666) 666-6666]">
      <![CDATA[java.lang.Exception: java.lang.AssertionError: expected [(111) 111-1111] but found [(666) 666-6666]
at Test.Ancera.Administration.OrganizationManagement.SearchUpdateOrganization(OrganizationManagement.java:629)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.AssertionError: expected [(111) 111-1111] but found [(666) 666-6666]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at Test.Ancera.Administration.OrganizationManagement.SearchUpdateOrganization(OrganizationManagement.java:621)
... 28 more
]]>
    </failure>
  </testcase> <!-- SearchUpdateOrganization -->
  <testcase classname="Test.Ancera.Administration.OrganizationManagement" name="OrganizationSiteMandatoryCheck" time="12.194"/>
  <testcase classname="Test.Ancera.Administration.OrganizationManagement" name="SiteResetButton" time="2.263"/>
  <testcase classname="Test.Ancera.Administration.OrganizationManagement" name="CreateOrganizationSite" time="7.543"/>
  <testcase classname="Test.Ancera.Administration.OrganizationManagement" name="UpdateOrganizationSites" time="10.771"/>
  <testcase classname="Test.Ancera.Administration.OrganizationManagement" name="VerifyUpdateOrganizationSites" time="6.125"/>
  <testcase classname="Test.Ancera.Administration.OrganizationManagement" name="DeleteOrganizationSites" time="7.592"/>
  <testcase classname="Test.Ancera.Administration.OrganizationManagement" name="InActiveOrganization" time="7.654"/>
  <testcase classname="Test.Ancera.Administration.OrganizationManagement" name="VerifyInActiveOrganization" time="24.542"/>
  <testcase classname="Test.Ancera.Administration.OrganizationManagement" name="DeleteOrganization" time="28.462"/>
</testsuite> <!-- Default test -->
