<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-K0SFL7M" failures="0" tests="11" name="Test.Ancera.Reports.Sites_Log" time="860.375" errors="1" timestamp="2022-02-14T18:22:22 PKT" skipped="0">
  <testcase classname="Test.Ancera.Reports.Sites_Log" name="NavigateSites" time="14.122"/>
  <system-out/>
  <testcase classname="Test.Ancera.Reports.Sites_Log" name="TestFilter" time="160.425"/>
  <system-out/>
  <testcase classname="Test.Ancera.Reports.Sites_Log" name="wildcard" time="245.654"/>
  <system-out/>
  <testcase classname="Test.Ancera.Reports.Sites_Log" name="SitesLock" time="229.206"/>
  <system-out/>
  <testcase classname="Test.Ancera.Reports.Sites_Log" name="Pagination" time="17.024"/>
  <system-out/>
  <testcase classname="Test.Ancera.Reports.Sites_Log" name="RowsPerPage" time="16.912"/>
  <system-out/>
  <testcase classname="Test.Ancera.Reports.Sites_Log" name="Sorting" time="0.369"/>
  <system-out/>
  <testcase classname="Test.Ancera.Reports.Sites_Log" name="AllignmentTest" time="0.344"/>
  <system-out/>
  <testcase classname="Test.Ancera.Reports.Sites_Log" name="FieldAccess" time="152.516"/>
  <system-out/>
  <testcase classname="Test.Ancera.Reports.Sites_Log" name="CSVExport" time="13.679">
    <error message="java.lang.AssertionError: expected [Sites Log - 20220214_1822.csv] but found [Coccidia Log - 20220214_1822.csv]" type="java.lang.Exception">
      <![CDATA[java.lang.Exception: java.lang.AssertionError: expected [Sites Log - 20220214_1822.csv] but found [Coccidia Log - 20220214_1822.csv]
at Test.Ancera.Reports.Sites_Log.CSVExport(Sites_Log.java:1046)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.AssertionError: expected [Sites Log - 20220214_1822.csv] but found [Coccidia Log - 20220214_1822.csv]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at Test.Ancera.Reports.Sites_Log.CSVExport(Sites_Log.java:981)
... 28 more
]]>
    </error>
  </testcase> <!-- CSVExport -->
  <system-out/>
  <testcase classname="Test.Ancera.Reports.Sites_Log" name="CSVAuditExport" time="10.124"/>
  <system-out/>
</testsuite> <!-- Test.Ancera.Reports.Sites_Log -->
