<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-K0SFL7M" failures="0" tests="19" name="Test.Ancera.Reports.CoccidiaLog" time="3259.684" errors="1" timestamp="2021-10-07T12:41:51 PKT" skipped="1">
  <testcase classname="Test.Ancera.Reports.CoccidiaLog" name="NavigateCoccidia" time="19.256"/>
  <system-out/>
  <testcase classname="Test.Ancera.Reports.CoccidiaLog" name="DateFilter" time="144.632"/>
  <system-out/>
  <testcase classname="Test.Ancera.Reports.CoccidiaLog" name="DateLockFilter" time="21.185"/>
  <system-out/>
  <testcase classname="Test.Ancera.Reports.CoccidiaLog" name="TestFilter" time="554.044"/>
  <system-out/>
  <testcase classname="Test.Ancera.Reports.CoccidiaLog" name="SiteName" time="31.698"/>
  <system-out/>
  <testcase classname="Test.Ancera.Reports.CoccidiaLog" name="wildcard" time="775.313"/>
  <system-out/>
  <testcase classname="Test.Ancera.Reports.CoccidiaLog" name="Contexual" time="353.436"/>
  <system-out/>
  <testcase classname="Test.Ancera.Reports.CoccidiaLog" name="CoccidiaLock" time="609.154"/>
  <system-out/>
  <testcase classname="Test.Ancera.Reports.CoccidiaLog" name="Pagination" time="16.070"/>
  <system-out/>
  <testcase classname="Test.Ancera.Reports.CoccidiaLog" name="RowsPerPage" time="45.057"/>
  <system-out/>
  <testcase classname="Test.Ancera.Reports.CoccidiaLog" name="Sorting" time="155.657"/>
  <system-out/>
  <testcase classname="Test.Ancera.Reports.CoccidiaLog" name="AllignmentTest" time="0.301"/>
  <system-out/>
  <testcase classname="Test.Ancera.Reports.CoccidiaLog" name="FieldAccess" time="434.532"/>
  <system-out/>
  <testcase classname="Test.Ancera.Reports.CoccidiaLog" name="FieldAccessResetDefault" time="6.122"/>
  <system-out/>
  <testcase classname="Test.Ancera.Reports.CoccidiaLog" name="PNGExport" time="28.395"/>
  <system-out/>
  <testcase classname="Test.Ancera.Reports.CoccidiaLog" name="CSVExport" time="48.173">
    <error message="java.lang.AssertionError: expected [Coccidia Log - 20211007_1241.csv] but found [Coccidia Log - 20211007_1240.csv]" type="java.lang.Exception">
      <![CDATA[java.lang.Exception: java.lang.AssertionError: expected [Coccidia Log - 20211007_1241.csv] but found [Coccidia Log - 20211007_1240.csv]
at Test.Ancera.Reports.CoccidiaLog.CSVExport(CoccidiaLog.java:1536)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.AssertionError: expected [Coccidia Log - 20211007_1241.csv] but found [Coccidia Log - 20211007_1240.csv]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at Test.Ancera.Reports.CoccidiaLog.CSVExport(CoccidiaLog.java:1509)
... 28 more
]]>
    </error>
  </testcase> <!-- CSVExport -->
  <system-out/>
  <testcase classname="Test.Ancera.Reports.CoccidiaLog" name="CSVAuditExport" time="9.695"/>
  <system-out/>
  <testcase classname="Test.Ancera.Reports.CoccidiaLog" name="TemplateExport" time="6.964"/>
  <system-out/>
  <testcase classname="Test.Ancera.Reports.CoccidiaLog" name="Assertion">
    <skipped/>
  </testcase> <!-- Assertion -->
  <system-out/>
</testsuite> <!-- Test.Ancera.Reports.CoccidiaLog -->
