<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-K0SFL7M" failures="0" tests="20" name="Test.Ancera.Reports.SalmonellaLog" time="97.846" errors="1" timestamp="2021-06-30T14:28:36 PKT" skipped="18">
  <testcase classname="Test.Ancera.Reports.SalmonellaLog" name="NavigateSalmonella" time="49.078"/>
  <system-out/>
  <testcase classname="Test.Ancera.Reports.SalmonellaLog" name="TestFilter" time="48.768">
    <error message="java.lang.AssertionError: expected [1] but found [0]" type="java.lang.Exception">
      <![CDATA[java.lang.Exception: java.lang.AssertionError: expected [1] but found [0]
at Test.Ancera.Reports.SalmonellaLog.TestFilter(SalmonellaLog.java:797)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.AssertionError: expected [1] but found [0]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at Test.Ancera.Reports.SalmonellaLog.TestFilter(SalmonellaLog.java:788)
... 28 more
]]>
    </error>
  </testcase> <!-- TestFilter -->
  <system-out/>
  <testcase classname="Test.Ancera.Reports.SalmonellaLog" name="RunAPI">
    <skipped/>
  </testcase> <!-- RunAPI -->
  <system-out/>
  <testcase classname="Test.Ancera.Reports.SalmonellaLog" name="DateFilter">
    <skipped/>
  </testcase> <!-- DateFilter -->
  <system-out/>
  <testcase classname="Test.Ancera.Reports.SalmonellaLog" name="AuditLog1">
    <skipped/>
  </testcase> <!-- AuditLog1 -->
  <system-out/>
  <testcase classname="Test.Ancera.Reports.SalmonellaLog" name="TestFilters">
    <skipped/>
  </testcase> <!-- TestFilters -->
  <system-out/>
  <testcase classname="Test.Ancera.Reports.SalmonellaLog" name="RowsPerPage">
    <skipped/>
  </testcase> <!-- RowsPerPage -->
  <system-out/>
  <testcase classname="Test.Ancera.Reports.SalmonellaLog" name="PNGExport">
    <skipped/>
  </testcase> <!-- PNGExport -->
  <system-out/>
  <testcase classname="Test.Ancera.Reports.SalmonellaLog" name="FieldAccessDrag">
    <skipped/>
  </testcase> <!-- FieldAccessDrag -->
  <system-out/>
  <testcase classname="Test.Ancera.Reports.SalmonellaLog" name="ResetFilter">
    <skipped/>
  </testcase> <!-- ResetFilter -->
  <system-out/>
  <testcase classname="Test.Ancera.Reports.SalmonellaLog" name="FieldAccessUnview">
    <skipped/>
  </testcase> <!-- FieldAccessUnview -->
  <system-out/>
  <testcase classname="Test.Ancera.Reports.SalmonellaLog" name="TemplateExport">
    <skipped/>
  </testcase> <!-- TemplateExport -->
  <system-out/>
  <testcase classname="Test.Ancera.Reports.SalmonellaLog" name="Pagination">
    <skipped/>
  </testcase> <!-- Pagination -->
  <system-out/>
  <testcase classname="Test.Ancera.Reports.SalmonellaLog" name="FieldAccessView">
    <skipped/>
  </testcase> <!-- FieldAccessView -->
  <system-out/>
  <testcase classname="Test.Ancera.Reports.SalmonellaLog" name="AuditLog">
    <skipped/>
  </testcase> <!-- AuditLog -->
  <system-out/>
  <testcase classname="Test.Ancera.Reports.SalmonellaLog" name="DateLockFilter">
    <skipped/>
  </testcase> <!-- DateLockFilter -->
  <system-out/>
  <testcase classname="Test.Ancera.Reports.SalmonellaLog" name="SalmonellaLock">
    <skipped/>
  </testcase> <!-- SalmonellaLock -->
  <system-out/>
  <testcase classname="Test.Ancera.Reports.SalmonellaLog" name="CSVExport">
    <skipped/>
  </testcase> <!-- CSVExport -->
  <system-out/>
  <testcase classname="Test.Ancera.Reports.SalmonellaLog" name="Sorting">
    <skipped/>
  </testcase> <!-- Sorting -->
  <system-out/>
  <testcase classname="Test.Ancera.Reports.SalmonellaLog" name="EnterDate">
    <skipped/>
  </testcase> <!-- EnterDate -->
  <system-out/>
</testsuite> <!-- Test.Ancera.Reports.SalmonellaLog -->
